sudo: false

language: rust

cache: cargo

rust:
  - stable

os:
  - linux
  - osx
  
script:
  - cargo build --release --all-features
  - cargo test --all --release --all-features
  - cargo build --benches --all --release --all-features
  - cargo bench  --all-features
  - cargo doc --release --all --no-deps --all-features

branches:
  only: master