[package]
name = "fn_block"
version = "0.1.0"
authors = ["Max Bureck <max.bureck@fokus.fraunhofer.de>"]
license = "Apache-2.0/MIT"

[dependencies]

[dev-dependencies]
criterion = "0.2.3"

[[bench]]
name = "fn_block_benchmark"
harness = false
